---
- name: Provision EC2 instance and launch Docker container
# serial: 1
  become: true
  hosts: localhost
  vars_files:
    - vars/keys.yml
    - vars/tower_ec2_var.yml

  tasks: 
    - name: Launch ec2 instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: us-east-1
        #region: "{{ AWS_REGION }}"
        instance_type: "{{ INSTANCE }}"
        key_name: "{{ KEY_NAME }}"
        image: "{{ BASE_AMI }}" #Centos7
        user_data: "{{ lookup('file', '/home/ansible/ansible-tower-setup/files/ans_env.sh')}}"
        assign_public_ip: yes
        group: "{{ GRP_NAME }}"
        vpc_subnet_id: "{{ default_vpc_subnet }}"
        wait: yes
        count: 1
        instance_tags:
          Name: Ansible-Tower
          image: yes
      register: ec2

    - debug: msg={{ ec2.instances }}

    - name: Add new created instance to inventory
      local_action: lineinfile
                    dest=./inventories/hosts
                    regexp={{ item.public_ip }}
                    insertafter="[tower]"
                    line={{ item.public_ip }}
      with_items: "{{ ec2.instances }}"
  
    - name: wait for SSH to come up
      local_action: wait_for
                    host={{ item.public_ip }}
                    port=22
                    state=started
      with_items: "{{ ec2.instances }}"
  
    - name: Make host_key_checking_false
      replace:
        path: /etc/ansible/ansible.cfg
        regexp: '^#host_key_checking = True'
        replace: 'host_key_checking = False'
        backup: yes

#    - name: debug ec2 registeerd variable
 #     debug: var={{ ec2.instances.public_ip }}

     
