---
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_default_ipv4.address }} >> cluster_initialized.txt
  args: 
    chdir: $HOME
    creates: cluster_initialized.txt
  delegate_to: "{{ hostvars['master'] }}"

- name: create .kube directory 
  file: 
    path: $HOME/.kube
    state: directory
    mode: 0755
  delegate_to: "{{ hostvars['master'] }}"

- name: copy admin.conf to users kube config
  copy: 
    src: /etc/kubernetes/admin.conf
    dest: /home/centos/.kube/config
    remote_src: yes
  delegate_to: "{{ hostvars['master'] }}"
    
- name: Install POD network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args: 
    chdir: $HOME
    creates: pod_network_setup.txt
  delegate_to: "{{ hostvars['master'] }}"
   #  delegate_to: "{{ groups['master'][0] }}"
   #

