---
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_default_ipv4.address } >> cluster_initialized.txt
  args: 
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory 
  file: 
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy 

